version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile   # Gebruik Dockerfile
    container_name: Cinema
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html   # html is de map op de host, /var/www/html is de map in de container
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:8.1
    container_name: mysql-db-Cinema
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-Cinema
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
